version: '3.7'

services:
  django:
    build: .
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn financeiro.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_NAME=financeiro
      - DB_USER=user_financeiro
      - DB_PASSWORD=123456
      - DB_HOST=postgres
      - DB_PORT=5432

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=financeiro
      - PGPORT=5432
      - POSTGRES_USER=user_financeiro
    restart: "on-failure"

volumes:
  postgres_data:
