# Generated by Django 4.0.4 on 2022-04-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agendado_para', models.DateTimeField(null=True)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('quitado', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Negociando'), (2, 'Agendado'), (3, 'Realizado'), (4, 'Em escolha'), (5, 'Em tratamento'), (6, 'Entregue'), (7, 'Cancelado')], default=1)),
                ('url_galeria', models.URLField()),
                ('gratuito', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotivoCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fone', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram_user', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_user', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data_lancamento', models.DateTimeField(auto_now=True)),
                ('tipo_lancamento', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], default='C', max_length=1)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.evento')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimentacao.formapagamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.pessoa'),
        ),
        migrations.AddField(
            model_name='evento',
            name='motivo_cancelamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movimentacao.motivocancelamento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimentacao.tipoevento'),
        ),
    ]
