# Generated by Django 4.0.3 on 2022-04-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectWithDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='gratuito',
            field=models.BooleanField(default=False),
        ),
    ]
