# Generated by Django 4.0.3 on 2022-03-27 00:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendado_para', models.DateTimeField(null=True)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('quitado', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Negociando'), (2, 'Agendado'), (3, 'Realizado'), (4, 'Em escolha'), (5, 'Em tratamento'), (6, 'Entregue'), (7, 'Cancelado')], default=1)),
                ('url_galeria', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MotivoCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('instagram_user', models.CharField(max_length=100)),
                ('facebook_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movimentacaofinanceira',
            name='agendado_para',
        ),
        migrations.RemoveField(
            model_name='movimentacaofinanceira',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='movimentacaofinanceira',
            name='valor_cobrado',
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='data_lancamento',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='forma_pagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='movimentacao.formapagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='tipo_lancamento',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemMovimentacao',
        ),
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.pessoa'),
        ),
        migrations.AddField(
            model_name='evento',
            name='motivo_cancelamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movimentacao.motivocancelamento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimentacao.tipoevento'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movimentacao.evento'),
            preserve_default=False,
        ),
    ]
