# Generated by Django 4.0.4 on 2022-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='descricao',
            field=models.CharField(error_messages={'blank': 'A descrição da forma de pagamento é obrigatória!'}, max_length=30, unique=True),
        ),
    ]
