# Generated by Django 4.0.4 on 2022-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0002_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='agendado_para',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
