# Generated by Django 4.0.3 on 2022-03-27 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0002_evento_motivocancelamento_pessoa_tipoevento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 27, 6, 37, 51, 88247, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
