# Generated by Django 4.0.3 on 2022-04-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0002_objectwithdescription_evento_gratuito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectWithDescription',
        ),
    ]
