# Generated by Django 4.0.3 on 2022-04-11 14:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0003_delete_objectwithdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='facebook_user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='fone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='instagram_user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
