# Generated by Django 4.0.3 on 2022-04-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0004_alter_pessoa_email_alter_pessoa_facebook_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='fone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
