# Generated by Django 4.0.4 on 2022-05-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0005_movimentacaofinanceira_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='data_lancamento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='tipo_lancamento',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], max_length=1),
        ),
    ]
